[[language]]
name = "cpp"
scope = "source.cpp"
file-types = ["cpp", "cc", "cxx", "hpp", "hh", "hxx"]
shebangs = ["g++", "clang++"]
roots = ["compile_commands.json", "build", ".git"]

# Configuration for the Language Server Protocol (LSP)
[language-server.cpp]
# The command to execute the clangd language server
command = "clangd"
args = ["--query-driver=/home/timo/.conan2/p/b/arm-n2c1d32c468465/p"]

